### ISSUE TITLE
Task: July 7th To-Do List

### ISSUE THREAD

**Issue by ianchadd** [ianchadd/rpi_3208#113]
- [x] RII edits
- [ ] QCP instructions edits
- [x] NBO Pilot Payment
- [x] NBO Pilot Analysis
