### ISSUE TITLE
Checklist for Deployment to Prolific

### ISSUE THREAD

**Issue by ianchadd** [ianchadd/rpi_3208#64]
- [ ] Create study on Prolific
- [ ] Create session in oTree
- [ ] Double-check the Prolific completion code link
- [ ] Double-check the URL on Prolific matches the session URL in Otree
- [ ] Check that PROLIFIC_ID and STUDY_ID are appended to URL in Prolific
- [ ] Send out link to researchers to go through code once more (only for short experiments)
- [ ] Make sure DEBUG mode is off in Heroku

**Comment by ianchadd** [comment]
@mcdaij can you add a checklist page with this info to the Wiki? Once it's done, update this ticket, I'll review and then close this. Thanks!
